#!/bin/sh

if [ $1 == "deep" ]; then
	pdflatex report
	bibtex report
	pdflatex report
	pdflatex report
elif [ $1 == "toc" ]; then
	pdflatex report
	pdflatex report
elif [[ $1 == "clean" ]]; then
	rm report.bbl report.blg report.toc report.aux report.log report.pdf
else
	pdflatex report
fi

